int _putchar(char f);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int _sqrtfinder(int f, int m);
int _is_prime_number(int n);
int is_divisible(int f, int div);
int is_palindrome(char *s);
int get_len(char *s);
int mr_pal(char *s, int f);
int wildcard(char *s1, char *s2);
